(title TINGLe Dropback 1)
(composer )
(show )
(year )
(comments )
(meter 4 4)
(key 0)
(tempo 160.0)
(volume 127)
(playback-transpose 0)
(chord-font-size 16)
(bass-instrument 33)
(bass-volume 50)
(drum-volume 36)
(chord-volume 54)
(breakpoint 54)
(layout)
(style swing
    (swing 0.67)
    (comp-swing 0.67)
    (bass-high g-)
    (bass-low c---)
    (bass-base e--)
    (chord-high a)
    (chord-low d-)
    (chord-base c- e- g-)
)
(part
    (type chords)
    (title )
    (composer )
    (instrument 0)
    (volume 65)
    (key 0)
)

(section (style swing)) 

CM7 | F7 | Bb7 | A7 | 

(part
    (type melody)
    (title )
    (composer )
    (instrument 11)
    (volume 85)
    (key 0)
    (stave treble)
)
 r1+1+1+1
