/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package imp.gui;

import java.util.Enumeration;
import javax.swing.AbstractButton;
import javax.swing.JRadioButton;

/**
 *
 * @author muddCS15
 */
public class PassiveTradingWindow extends javax.swing.JFrame {

    private Notate notate;
    
    /**
     * The numeric values of the bars to be traded.
     */
    private static int tradingQuantum[] = {1, 2, 4, 8, 12, 16};
    
    /**
     * Creates new form PassiveTradingWindow
     */
    public PassiveTradingWindow(Notate notate) {
        this.notate = notate;
        initComponents();
    }
    
    public boolean getImprovisorTradeFirst(){
        return improvisorFirst.isSelected();
    }
    
    public int getTradingQuantum(){
      Enumeration<AbstractButton> bars = numberOfBarsGroup.getElements();
      for(int i = 0; i < numberOfBarsGroup.getButtonCount(); i++){
          JRadioButton button = (JRadioButton) bars.nextElement();
          if(button.isSelected()){
              return tradingQuantum[i]*notate.getScore().getSlotsPerMeasure();
              //return ((Integer)wordToNumber.get(button.getText()))*score.getSlotsPerMeasure();
          }
      }
      return notate.getScore().getSlotsPerMeasure(); // default
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        whoPlaysFirstGroup = new javax.swing.ButtonGroup();
        numberOfBarsGroup = new javax.swing.ButtonGroup();
        whoGoesFirstLabel = new javax.swing.JLabel();
        tradeLengthLabel = new javax.swing.JLabel();
        whoGoesFirstPanel = new javax.swing.JPanel();
        improvisorFirst = new javax.swing.JRadioButton();
        userFirst = new javax.swing.JRadioButton();
        tradeLengthPanel = new javax.swing.JPanel();
        one = new javax.swing.JRadioButton();
        two = new javax.swing.JRadioButton();
        four = new javax.swing.JRadioButton();
        eight = new javax.swing.JRadioButton();
        twelve = new javax.swing.JRadioButton();
        sixteen = new javax.swing.JRadioButton();

        setMaximumSize(new java.awt.Dimension(400, 300));
        setMinimumSize(new java.awt.Dimension(400, 300));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        whoGoesFirstLabel.setText("Who Goes First:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        getContentPane().add(whoGoesFirstLabel, gridBagConstraints);

        tradeLengthLabel.setText("Trade Length in Bars:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        getContentPane().add(tradeLengthLabel, gridBagConstraints);

        whoGoesFirstPanel.setLayout(new java.awt.GridBagLayout());

        whoPlaysFirstGroup.add(improvisorFirst);
        improvisorFirst.setSelected(true);
        improvisorFirst.setText("Impro-Visor First");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        whoGoesFirstPanel.add(improvisorFirst, gridBagConstraints);

        whoPlaysFirstGroup.add(userFirst);
        userFirst.setText("User First");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        whoGoesFirstPanel.add(userFirst, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        getContentPane().add(whoGoesFirstPanel, gridBagConstraints);

        tradeLengthPanel.setLayout(new java.awt.GridBagLayout());

        numberOfBarsGroup.add(one);
        one.setSelected(true);
        one.setText("one");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        tradeLengthPanel.add(one, gridBagConstraints);

        numberOfBarsGroup.add(two);
        two.setText("two");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        tradeLengthPanel.add(two, gridBagConstraints);

        numberOfBarsGroup.add(four);
        four.setText("four");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        tradeLengthPanel.add(four, gridBagConstraints);

        numberOfBarsGroup.add(eight);
        eight.setText("eight");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        tradeLengthPanel.add(eight, gridBagConstraints);

        numberOfBarsGroup.add(twelve);
        twelve.setText("twelve");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        tradeLengthPanel.add(twelve, gridBagConstraints);

        numberOfBarsGroup.add(sixteen);
        sixteen.setText("sixteen");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        tradeLengthPanel.add(sixteen, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        getContentPane().add(tradeLengthPanel, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton eight;
    private javax.swing.JRadioButton four;
    private javax.swing.JRadioButton improvisorFirst;
    private javax.swing.ButtonGroup numberOfBarsGroup;
    private javax.swing.JRadioButton one;
    private javax.swing.JRadioButton sixteen;
    private javax.swing.JLabel tradeLengthLabel;
    private javax.swing.JPanel tradeLengthPanel;
    private javax.swing.JRadioButton twelve;
    private javax.swing.JRadioButton two;
    private javax.swing.JRadioButton userFirst;
    private javax.swing.JLabel whoGoesFirstLabel;
    private javax.swing.JPanel whoGoesFirstPanel;
    private javax.swing.ButtonGroup whoPlaysFirstGroup;
    // End of variables declaration//GEN-END:variables
}
