/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package imp.gui;
import imp.trading.ActiveTradingDialog;

/**
 *
 * @author cssummer17
 */
public class TransformMenuDialog extends javax.swing.JDialog {

     Notate notate;
     ActiveTradingDialog activeTradingDialog;
     javax.swing.DefaultListModel transformListModel = new javax.swing.DefaultListModel();
     String musician = "";
    
    /**
     * Creates new form TransformMenuDialog
     */
    public TransformMenuDialog(Notate notate, boolean modal) {
        super(notate, modal);
        initComponents();
        this.setTitle("Transform Menu");
        this.notate = notate;
    }

    public javax.swing.JList getTransformList()
    {
        return transformJlist;
    }
    
    public javax.swing.DefaultListModel getTransformListModel()
    {
        return transformListModel;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        transformListScrollPane = new javax.swing.JScrollPane();
        transformJlist = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(new java.awt.GridBagLayout());

        transformListScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        transformListScrollPane.setAutoscrolls(true);
        transformListScrollPane.setDoubleBuffered(true);
        transformListScrollPane.setHorizontalScrollBar(null);
        transformListScrollPane.setMinimumSize(new java.awt.Dimension(300, 100));
        transformListScrollPane.setName("Transform Menu"); // NOI18N
        transformListScrollPane.setPreferredSize(new java.awt.Dimension(300, 600));

        transformJlist.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        transformJlist.setModel(transformListModel);
        transformJlist.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        transformJlist.setToolTipText("");
        transformJlist.setBounds(new java.awt.Rectangle(0, 0, 300, 600));
        transformJlist.setName(""); // NOI18N
        transformJlist.setVisibleRowCount(200);
        transformJlist.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                transformJlistMouseClicked(evt);
            }
        });
        transformListScrollPane.setViewportView(transformJlist);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(transformListScrollPane, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void transformJlistMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transformJlistMouseClicked
        //transformAction();
       int index = transformJlist.getSelectedIndex();
       musician = (String) transformListModel.getElementAt(index);
       //System.out.println("selected musician: " + musician);
       notate.updateMusicianNotate(musician);
       //activeTradingDialog.setTransformStatusButtonText(musician);
       //activeTradingDialog.updateMusician(musician);
       //activeTradingDialog.getActiveTrading().setMusician(musician);
      // activeTradingDialog.getTransformStatusButton().setText("" + musician);
    }//GEN-LAST:event_transformJlistMouseClicked
   
    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        transformListModel.clear();
    }//GEN-LAST:event_formWindowClosed

    public String getMusicianName()
    {
        return musician;
    }
    
//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(TransformMenuDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(TransformMenuDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(TransformMenuDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(TransformMenuDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                TransformMenuDialog dialog = new TransformMenuDialog(this.notate, true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> transformJlist;
    private javax.swing.JScrollPane transformListScrollPane;
    // End of variables declaration//GEN-END:variables
}
